version: '3.4'

services:

  exercicio02.app:
    container_name: exercicio02_app
    image: ${REGISTRY:-provanpf}/exercicio02app:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Exercicio02.App/Dockerfile
    depends_on:
      - "exercicio02.database"

  exercicio02.database:
    container_name: exercicio02_database
    image: ${REGISTRY:-provanpf}/exercicio02database:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Exercicio02/Dockerfile
    ports:
      - "5433:1433"
#   volumes:
#      - mssqldata:/var/opt/mssqldata


  exercicio03.api:
    image: ${REGISTRY:-provanpf}/exercicio03api:${PLATFORM:-linux}-${TAG:-latest}
    container_name: exercicio03_api
    build:
      context: .
      dockerfile: Exercicio03.API/Dockerfile
    depends_on:
      - "exercicio03.cache"

  exercicio03.cache:
    image: redis
    container_name: exercicio03_cache
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

# volumes:
#  mssqldata: 